config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'rides#index'
  get "dashboard/index"

  resources :rides

end

app/models/authentication_provider.rb
class AuthenticationProvider < ActiveRecord::Base
  has_many :users
  has_many :user_authentications
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  validates :user_id, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_from_omniauth(params)
    attributes = {
      email: params['info']['email'],
      password: Devise.friendly_token
    }

    create(attributes)
  end

  has_many :authentications, class_name: 'UserAuthentication', dependent: :destroy
  has_many :rides, dependent: :destroy

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_authentication.rb
class UserAuthentication < ActiveRecord::Base
  belongs_to :user
  belongs_to :authentication_provider

  serialize :params

  def self.create_from_omniauth(params, user, provider)
    token_expires_at = params['credentials']['expires_at'] ? Time.at(params['credentials']['expires_at']).to_datetime : nil

    create(
      user: user,
      authentication_provider: provider,
      uid: params['uid'],
      token: params['credentials']['token'],
      token_expires_at: token_expires_at,
      params: params,
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  
    @a2b_distance = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: "Distance from point A to B")
      f.xAxis(categories: get_from)
      f.series(name: "Distance in Kilometers", yAxis: 0, data: Ride.pluck(:distance))

      f.yAxis [
        {title: {text: "Distance in Kilometers", margin: 30} },
      ]

      f.chart({defaultSeriesType: "line"})
    end

    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, "rgb(255, 255, 255)"],
            [1, "rgb(240, 240, 255)"]
          ]
        },
        borderWidth: 2,
        plotBackgroundColor: "rgba(255, 255, 255, .9)",
        plotShadow: true,
        plotBorderWidth: 1
      )
      f.lang(thousandsSep: ",")
      f.colors(["#90ed7d", "#f7a35c", "#8085e9", "#f15c80", "#e4d354"])
    end
    
  end
  
  def get_from
    from = []
    Ride.find_each do |data|
      from.push("#{data['from']} to #{data['to']}")
    end
    return from
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end
end  

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ride, only: [:show, :edit, :update, :destroy]
  before_action :owned_ride, only: [:edit, :update, :destroy]  

  # GET /rides
  # GET /rides.json
  # GET /rides.xml
  def index
    @rides = Ride.all
    
    #http://api.rubyonrails.org/classes/ActionController/MimeResponds.html
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @rides }
      format.json { render :json => @rides }
    end
  end

  # GET /rides/1
  # GET /rides/1.json
  # GET /rides/1.xml
  def show
    #http://guides.rubyonrails.org/layouts_and_rendering.html#using-render
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @ride }
      format.json { render :json => @ride }
    end
  end

  # GET /rides/new
  def new
    @ride = current_user.rides.build
  end
  

  # GET /rides/1/edit
  def edit
  end
  
  
  # POST /rides
  # POST /rides.json
  def create

    @ride = current_user.rides.build(ride_params)
    get_distance(@ride)

    respond_to do |format|
      if @ride.save
        format.html { 
          flash[:success] = "Your ride has been created!"
          redirect_to root_path
          #redirect_to @ride, notice: 'Ride was successfully created.' 
          }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { 
          flash[:alert] = "Your new ride couldn't be created! Please check the form"
          render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      get_distance(@ride)
      if @ride.update(ride_params)
        format.html { 
          flash[:success] = "Ride updated."
          redirect_to root_path }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { 
          flash[:alert] = "Update failed.  Please check the form."
          render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { 
        flash[:success] = "Your ride has been deleted."
        redirect_to root_path }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:from, :to, :date, :time, :distance)
    end
  
    def owned_ride  
      unless current_user == @ride.user
        flash[:alert] = "That ride doesn't belong to you!"
        redirect_to root_path
      end
    end  
  
  def get_distance(ride)
    response = HTTParty.get("http://maps.googleapis.com/maps/api/directions/json?origin=#{ride.from}&destination=#{ride.to}")
    body = JSON.parse(response.body)
    if body['status'] != "NOT_FOUND"
      distance_meters = body['routes'][0]['legs'][0]['distance']['value']
      ride.distance = distance_meters/1000
    else
      ride.distance = 0
    end
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    create
  end

  #def twitter
  #  create
  #end
  
  def google_oauth2
    create
  end

  private

    def create
      auth_params = request.env["omniauth.auth"]
      provider = AuthenticationProvider.where(name: auth_params.provider).first
      authentication = provider.user_authentications.where(uid: auth_params.uid).first
      existing_user = current_user || User.where('email = ?', auth_params['info']['email']).first

      if authentication
        sign_in_with_existing_authentication(authentication)
      elsif existing_user
        create_authentication_and_sign_in(auth_params, existing_user, provider)
      else
        create_user_and_authentication_and_sign_in(auth_params, provider)
      end
    end

    def sign_in_with_existing_authentication(authentication)
      sign_in_and_redirect(:user, authentication.user)
    end

    def create_authentication_and_sign_in(auth_params, user, provider)
      UserAuthentication.create_from_omniauth(auth_params, user, provider)

      sign_in_and_redirect(:user, user)
    end

    def create_user_and_authentication_and_sign_in(auth_params, provider)
      user = User.create_from_omniauth(auth_params)
      if user.valid?
        create_authentication_and_sign_in(auth_params, user, provider)
      else
        flash[:error] = user.errors.full_messages.first
        redirect_to new_user_registration_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def alert_for(flash_type)
    {
      success: 'alert-success text-center',
      error: 'alert-danger text-center',
      alert: 'alert-warning text-center',
      notice: 'alert-info text-center'
    }[flash_type.to_sym] || flash_type.to_s
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/dashboard/index.html.haml
.container
  .row
    .col-md-4.col-md-offset-4
    = high_chart("1", @a2b_distance)

    

app/views/layouts/_navbar.html.haml
%body
  .container
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-brand
            = link_to "Rideshare", root_path
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Rides", root_path
            - if user_signed_in?
              %li
                = link_to "New Ride", new_ride_path
            %li
              = link_to "Dashboard", dashboard_index_path
          %%ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to "Profile", edit_user_registration_path
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Login", new_user_session_path
              %li
                = link_to "Register", new_user_registration_path
            

app/views/layouts/application.html.haml
%html
  %head
    %title RideShare
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = javascript_include_tag 'http://maps.googleapis.com/maps/api/js?key=AIzaSyCEAwSxlP1mC4SBQvLihO-DPJLIaZpk6xg&sensor=true'
  %body
    = render 'layouts/navbar'
    -flash.each do |name, msg|
      .container
        = content_tag :div, msg, class: [:alert, alert_for(name)]
    = yield

app/views/rides/_form.html.haml
.container
  .row
    .col-md-4.col-md-offset-4
      .log-in.panel
        = simple_form_for(@ride) do |f|
          = f.error_notification
          .panel-body
            = f.input :from, label:false, placeholder:"From", required: true, autofocus: true, input_html: { class: 'input-lg' }
            = f.input :to, label:false, placeholder:"To", required: true, autofocus: true, input_html: { class: 'input-lg' }
            = f.input :date, required: true, autofocus: true, input_html: { class: 'input-lg' }
            = f.input :time, required: true, autofocus: true, input_html: { class: 'input-lg' }
            = f.button :submit, class: 'btn btn-lg btn-success btn-block'
            = link_to 'Back', rides_path, :class => "btn btn-lg btn-primary btn-block"

app/views/rides/edit.html.haml
%h2.text-center Editing Ride
= render 'form'

app/views/rides/index.html.haml
.container
  .jumbotron
    %h2 Rides 
    %table.table-striped.table-responsive
      %thead
        %tr
          %th.col-md-2 From
          %th.col-md-2 To
          %th.col-md-2 Date
          %th.col-md-2 Time
          %th.col-md-2 Distance
      %tbody
        - @rides.each do |ride|
          %tr
            %td= ride.from
            %td= ride.to
            %td= ride.date.to_formatted_s(:long_ordinal)
            %td= ride.time.to_s(:time)
            %td= "#{ride.distance} km"
            - if current_user.id == ride.user_id
              %td.btn-group.btn-group-sm{"aria-label" => "Actions", :role => "group"}
                =link_to 'Show', ride, :class => "btn btn-secondary btn-success"
                =link_to 'Edit', edit_ride_path(ride), :class => "btn btn-secondary btn-warning"
                =link_to 'Destroy', ride, :class => "btn btn-secondary btn-danger", method: :delete, data: { confirm: 'Are you sure?' }
            - else
              %td= link_to 'Show', ride, :class => "btn btn-success btn-sm"

app/views/rides/new.html.haml
%h2.text-center New Ride
= render 'form'

app/views/rides/show.html.haml
.container
  .jumbotron
    %h2 Current Ride 
    %table.table-striped.table-responsive
      %thead
        %tr
          %th.col-md-2 From
          %th.col-md-2 To
          %th.col-md-2 Date
          %th.col-md-2 Time
          %th.col-md-2 Distance
          %th.col-md-2 Contact
      %tbody
        %tr
          %td= @ride.from
          %td= @ride.to
          %td= @ride.date.to_formatted_s(:long_ordinal)
          %td= @ride.time.to_s(:time)
          %td= "#{@ride.distance} km"
          %td= "#{User.find(@ride.user).email}"
    %br/
    = link_to 'Back', rides_path, :class => "btn btn-lg btn-primary"